# Usa una imagen base de Node.js
FROM node:22

# Establece el directorio de trabajo
WORKDIR /usr/src/app
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Copia los archivos de tu proyecto
COPY package*.json ./
COPY . .

# Instala las dependencias
RUN npm install --omit=dev

# Construye el proyecto
RUN npm run build

# Expone el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar el servidor en producción
CMD ["node", ".output/server/index.mjs"]
